#!/usr/bin/env sh
# vim:set expandtab shiftwidth=4 filetype=sh:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/pd-upload.git
# ::: :/.husky/commit-msg
#
#

bun run --bun commitlint --edit "$1"
